#!/usr/bin/env python
import rospy

from geometry_msgs.msg import Twist

import sys, select, termios, tty

msg = """
Control Your multiple Turtlebot!
---------------------------
Moving around:
   w
   a
   s
   d
q/z : increase/decrease max speeds by 10%
w/x : increase/decrease only linear speed by 10%
e/c : increase/decrease only angular speed by 10%
space key, k : force stop
anything else : stop smoothly

CTRL-C to quit
"""


def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

if __name__=="__main__":

   settings = termios.tcgetattr(sys.stdin)
    
   rospy.init_node('MultiRobot_teleop')
   pub = rospy.Publisher('~cmd_vel', Twist)
   rate = rospy.Rate(10)
   while not rospy.is_shutdown():
      twist = Twist()
      twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0
      twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0
      pub.publish(twist)

   termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)

